# Source: kuberhealthy/templates/khcheck-dns-internal.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-internal-service-crb
  annotations:
    meta.helm.sh/release-name: 'kuberhealthy'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dns-internal-service-cr
subjects:
- kind: ServiceAccount
  name: dns-internal-sa
  namespace: kuberhealthy
