apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - todo
    dockerRegistryOrg: stewartshea
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: registry.hub.docker.com
  environments:
  - key: dev
    owner: runwhen-contrib
    repository: sandbox-jenkinsx-cluster
  - key: staging
  - key: production
  ingress:
    domain: sandbox.runwhen.com
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: stewartshea
  repository: none
  secretStorage: local
  vault: {}
  webhook: lighthouse
