apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        runwhen/infra-flux-nonprod-sandbox-jx: true
        runwhen/infra-flux-nonprod-sandbox-jx-quickstart-golang-http: true
        runwhen/infra-flux-nonprod-sandbox-jx-quickstart-http: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        runwhen/infra-flux-nonprod-sandbox-jx: merge
        runwhen/infra-flux-nonprod-sandbox-jx-quickstart-golang-http: merge
        runwhen/infra-flux-nonprod-sandbox-jx-quickstart-http: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - runwhen/infra-flux-nonprod-sandbox-jx
        - runwhen/infra-flux-nonprod-sandbox-jx-quickstart-golang-http
        - runwhen/infra-flux-nonprod-sandbox-jx-quickstart-http
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - runwhen/infra-flux-nonprod-sandbox-jx
        - runwhen/infra-flux-nonprod-sandbox-jx-quickstart-golang-http
        - runwhen/infra-flux-nonprod-sandbox-jx-quickstart-http
      target_url: http://lighthouse-jx.sandbox.runwhen.com/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
